apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-12-19T13:51:01Z"
  generation: 1
  labels:
    app: nginx-deployment
  name: nginx-deployment
  namespace: default
  resourceVersion: "5978"
  uid: 4084c354-df23-41f5-b242-74e154c52531
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        volumeMounts:                                     # <-- änderung
        - name: config-volume                             # <-- änderung
          mountPath: /usr/share/nginx/html                # <-- änderung
        terminationMessagePath: /dev/termination-log      
        terminationMessagePolicy: File
      volumes:                                            # <-- änderung
      - name: config-volume                               # <-- änderung
        configMap:                                        # <-- änderung
          name: nginx-index                               # <-- änderung
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-12-19T13:51:03Z"
    lastUpdateTime: "2023-12-19T13:51:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-12-19T13:51:01Z"
    lastUpdateTime: "2023-12-19T13:51:03Z"
    message: ReplicaSet "nginx-deployment-6d6565499c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
